### ISSUE TITLE
编译成品jar的问题

### ISSUE THREAD

**Issue by liach** [Akarin-project/AkarinForge#1]
1、成品jar里面又有反混淆的类，也有重新混淆的类
2、成品jar里面有客户端专属类（gradle task里面检查的annotation错了，应该是`Lnet/minecraftforge/fml/relauncher/SideOnly`）

**Comment by Luohuayu** [comment]
不要消费过气服务端

**Comment by liach** [comment]
过气……我只是下载后看看而已，不知道已经弃坑。

**Comment by liach** [comment]
工程被清空了？
